import Image
import math
import os
import threading
import time

from optparse import OptionParser

b = 72 # baseline distance
f = 22 # focal length

min_color = 20
max_color = 235

left_theta = 1.5708
right_theta = 1.01129
left_alpha = 0.23022
right_alpha = 0.33389
frame_count = 96

image_size_x = 1280
image_size_y = 720

def rename_files(dir_name):
	""" This was an elaborate plan to rename image files.

	It was intended to be used to rename n images to
	"scan000, scan001, ... , scan[n-1]" but then I realized I
	didn't need to do this at all, so I didn't even finish
	writing the function. But I'll leave it in here in case I
	need it at some point and want to finish it."""

	# if not dir_name.endswith("/"):
	# 	dir_name = dir_name + "/"

	# if not os.listdir(dir_name):
	# 	print "directory is empty, dummy"
	# else:
	# 	os.mkdir(dir_name + "tmp")
	# 	for filename in os.listdir(dir_name):
	# 		os.rename(filename, "tmp/" + filename)

	print "You've selected the rename flag. It does nothing."

def scan_dir(dir_name):
	print "Processing scans in directory: " + dir_name
	print_divider()
	if not os.listdir(dir_name):
		print "Directory is empty, make sure there are scans here."
	else:
		first_scan = Image.open(dir_name + os.listdir(dir_name)[0])
		z_array = [[(0, 0, 0) for x in xrange(first_scan.size[1])] for x in xrange(first_scan.size[0])]

		thread_list = []

		print "Scanning images and creating z array..."
		print_divider()

		start_time = time.clock()

		scan_number = 0
		for filename in os.listdir(dir_name):
			t = threading.Thread(target=scan_image, args=(dir_name + filename, scan_number, z_array))
			thread_list.append(t)
			t.start()

			scan_number += 1

		for thread in thread_list:
			thread.join()

		output_pcd(z_array)

		end_time = time.clock()
		total_time = end_time - start_time
		print "scan finished in " + str(total_time) + "seconds."
		print str(total_time / len(os.listdir(dir_name))) + " seconds per frame."

def scan_image(filename, scan_number, z_array):
	print "opening file " + filename
	scan = Image.open(filename)

	for y in xrange(scan.size[1]):
		enter_white, exit_white = 0, 0
		for x in xrange(scan.size[0]):
			r, g, b = scan.getpixel((x, y))
			if is_white(r, g, b):
				enter_white = x
				break
		for x in xrange(enter_white, scan.size[0]):
			r, g, b = scan.getpixel((x, y))
			if not is_white(r, g, b):
				exit_white = x - 1
				break

		if enter_white != 0 and exit_white != 0:
			mid_white = int((enter_white + exit_white) / 2)
			z_array[mid_white][y] = z_triangulation(mid_white, y, scan_number)

def z_triangulation(x, y, scan_number):
	y = image_size_y - y
	theta = translate(scan_number, 0, frame_count - 1, left_theta, right_theta)
	alpha = translate(scan_number, 0, frame_count - 1, left_alpha, right_alpha)
	z = b * (math.sin(theta) / math.sin(alpha + theta))
	return x, y, z * (-f)


def red_blue_for_z(z, min_z, max_z):
	red = translate(z, min_z, max_z, min_color, max_color)
	blue = translate(z, min_z, max_z, max_color, min_color)

	return red, blue

def translate(value, leftMin, leftMax, rightMin, rightMax):
    leftSpan = leftMax - leftMin
    rightSpan = rightMax - rightMin

    valueScaled = float(value - leftMin) / float(leftSpan)

    return rightMin + (valueScaled * rightSpan)

def output_pcd(z_array):
	z_list = []
	for u in xrange(len(z_array)):
		for v in xrange(len(z_array[0])):
			point = z_array[u][v]
			if (point != (0, 0, 0)):
				z_list.append(point)

	pcd_file = open("output.pcd", "w")
	pcd_file.write("# .PCD v.7 -- file generated by structured_light_scan.py\n")
	pcd_file.write("VERSION .7\n")
	pcd_file.write("FIELDS x y z\n")
	pcd_file.write("SIZE 8 8 8\n")
	pcd_file.write("TYPE F F F\n")
	pcd_file.write("COUNT 1 1 1\n")
	pcd_file.write("WIDTH " + str(len(z_list)) + "\n")
	pcd_file.write("HEIGHT 1\n")
	pcd_file.write("VIEWPOINT 0 0 0 1 0 0 0\n")
	pcd_file.write("POINTS " + str(len(z_list)) + "\n")
	pcd_file.write("DATA ascii\n")

	for point in z_list:
		x, y, z = point
		pcd_file.write(str(x) + " " + str(y) + " " + str(z) + "\n")


def angle_for_frame(frame_number):
	return translate(frame_number, 0, frame_count - 1, left_theta, right_theta)

def is_white(r, g, b):
	if r == 255 and g == 255 and b == 255:
		return True
	else:
		return False

def print_divider():
	print "-----------------------------------------------------"

def fix_dir_name(dir_name):
	if dir_name.endswith("/"):
		return dir_name
	else:
		return dir_name + "/"

def clean_dir(dir_name):
	if ".DS_Store" in os.listdir(dir_name):
		os.remove(dir_name + ".DS_Store")

def main():
	parser = OptionParser()
	parser.add_option("-r", action="store_true", dest="rename")
	parser.add_option("-s", action="store_true", dest="scan")
	parser.add_option("-d", "--dir", dest="dir_name")

	(options, args) = parser.parse_args()

	if not options.dir_name:
		print "Need to specify directory with -d option"
	else:
		fixed_dir = fix_dir_name(options.dir_name)
		clean_dir(fixed_dir)

		if options.rename:
			rename_files(fixed_dir)

		if options.scan:
			scan_dir(fixed_dir)

if __name__ == "__main__":
	main()